### ISSUE TITLE
maxLength attribute on textarea is not fully adapted in mobile chrome(/browsers)

### ISSUE THREAD

**Issue by aidoskanapyanov** [aidoskanapyanov/linkedin-gpt#1]
When writing into a textarea on chrome, the amount of character is not limited to the value of maxlength attribute, it can go beyond that.

**Comment by maheshchandra10** [comment]
Thought of working on this issue and tried to reproduce it, but I am not able to enter more than 200 characters in the textarea (which probably is the `expected` behavior).

Is there anything different that is expected here?
@aidoskanapyanov 

![image](https://github.com/aidoskanapyanov/linkedin-gpt/assets/148360659/ccf7f7a4-07b2-4e27-8995-3eafbc72c7e2)

**Comment by aidoskanapyanov** [comment]
> Thought of working on this issue and tried to reproduce it, but I am not able to enter more than 200 characters in the textarea (which probably is the `expected` behavior).
> 
> Is there anything different that is expected here? @aidoskanapyanov
> 
> ![image](https://user-images.githubusercontent.com/148360659/277097645-ccf7f7a4-07b2-4e27-8995-3eafbc72c7e2.png)

Hi @maheshchandra10, thank you for your comment! Yes, it's difficult to reproduce. On my android google chrome it is possible to type beyond 200 characters. Here are the screenshots
![textarea](https://github.com/aidoskanapyanov/linkedin-gpt/assets/65722512/4509d1d8-ee9a-4e99-addc-4a1977233080)
![chrome](https://github.com/aidoskanapyanov/linkedin-gpt/assets/65722512/7702ad63-6c2e-420a-ba67-1629d334ae0a)

**Comment by aidoskanapyanov** [comment]
Maxlength used to be unstable on some versions of mobile chrome. Here's the link to SO thread. https://stackoverflow.com/a/38573322

I believe it would be good to limit the length on the input via JavaScript inside the component, to prevent the issue completely. One possible solution is to do nothing onChange event whenever the length of input equals to 200 or probably substring it to first 200 characters. PRs are welcome :)

**Comment by maheshchandra10** [comment]
So I tried searching for this issue and I found this- https://github.com/ionic-team/ionic-framework/issues/11578#issuecomment-323403990

So apparently it seems like it's a `keyboard issue of android` according to this comment.

Please let me know if I can give this issue a try.

**Comment by aidoskanapyanov** [comment]
That's interesting. Great find! Sure, you can work on this issue, thanks! 👍
